name: PR file guard

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-files:
    name: Validate PR file changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate changed files
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) throw new Error('This workflow must be run from a pull_request event');

            // List files changed in the PR (auto-paginates)
            const files = await github.paginate(github.rest.pulls.listFiles, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });

            const prohibited = new Set(['README.md', 'registration.py', '.gitignore', '.github/workflows/validate-pr.yml']);
            const errors = [];

            for (const f of files) {
              const filename = f.filename;
              const status = f.status; // added | removed | modified | renamed

              // Explicitly forbid touching certain files
              if (prohibited.has(filename)) {
                errors.push(`Changes to "${filename}" are not allowed.`);
              }

              // Disallow any changes to workflow files (no edits or new workflows)
              if (filename.startsWith('.github/workflows/')) {
                errors.push(`Changes to workflow files under .github/workflows/ are not allowed ("${filename}").`);
                continue;
              }

              // Only allow newly added files, and only under tickets/
              if (status !== 'added') {
                errors.push(`Only new files are allowed in pull requests. "${filename}" has status "${status}".`);
              } else if (!filename.startsWith('tickets/')) {
                errors.push(`New files are only allowed under the tickets/ directory. "${filename}" is not under tickets/.`);
              }
            }

            if (errors.length) {
              // Provide a helpful summary in the failure message
              const message = [
                'PR validation failed — file rules not satisfied:',
                ...errors,
                '',
                'Allowed changes: add new files under the tickets/ directory only.',
                'Disallowed: modifications, deletions, renames, or adding files outside tickets/, any changes to README.md or registration.py, and any changes or additions to .github/workflows/.',
              ].join('\n');

              throw new Error(message);
            }

            console.log('PR file validation passed — only allowed changes detected.');
